apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 'doc-example'
  description: 'Example of documentation for a UI'
  tags:
    - angular
    - frontend
  links:
    - title: Angular Home
      url: https://angular.io/
  annotations:
    github.com/project-slug: ysahbi/TechDocExample
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  system: car-order-system
  owner: operational-department
  consumesApis:
    - car-discount-api
    - car-information-api
